dist: trusty # fix for travis not updating their HHVM images
language: php
php:
  - 7.1

# only build master branch (and PRs)
branches:
  only:
    - "master"

script:
  # DEBUG
  - php -i
  - curl -v 'https://api.blocktrail.com/v1/BTC/price?api_key=MY_APIKEY'
  - php curl.php
